### PR TITLE
Remove wasted space on add measurement page

### PR DESCRIPTION
**Pull request by in-zare**

### CODE REVIEW

**Comment by mikepsinn** [comment]
@in-zare Beautiful!  Much nicer!  :D

**Comment by in-zare** [comment]
It's actually margin bottom 0, called it that way in case anywhere else it's needed just to make margin-bottom: 0 but i can update it's name

**Comment by mikepsinn** [comment]
Thanks!  Can we change to `margin-bottom-0` so it's more obvious?

**Comment by in-zare** [comment]
Sure, just updated it.

**Comment by mikepsinn** [comment]
Thanks!

**Pull request merged**
