### PR TITLE
Changes to CSS directory structure and reminder-add.html

### PR DESCRIPTION
**Pull request by oxideorcoal**
- Changed directory structure for CSS so SASS can be used, and `www/scss/app.scss` is now pulling SASS files from `www/lib`
- Removed extra white space and aligned text to right in `reminder-add.html`
- Updated `index.html` to use the `www/css/app.min.css` stylesheet 
- Removed duplicate SASS task from `gulpfile.js`
- Edited SASS task in `gulpfile.js` to reflect new directory structure
- Added documentation for SASS in the `docs` directory

### CODE REVIEW

**Comment by mikepsinn** [comment]
Thanks, @oxideorcoal !  Looks great!  Do you think there's a benefit to having Reminder and page-specific styles?  Should we just use a global stylesheet to make sure everything's consistent across pages throughout the app?

**Comment by oxideorcoal** [comment]
Yeah good point! Maybe we could use app.scss for all global styles, and then use the partials directory for page specific styles *if* they are needed?

**Comment by mikepsinn** [comment]
That sounds good to me!  Could you move anything that could be used globally before I merge?

**Comment by oxideorcoal** [comment]
Done! To me it looked like only a couple of the styles could be useful anywhere else but reminder-add.html, a lot of them were dependent on ID's that were only in reminder-add

**Comment by mikepsinn** [comment]
Thanks, @oxideorcoal !  :D Looks great!  I guess when we get time, we'll have to start using global classes instead of ids for those dates, times, and selectors since we have those in other pages as well.

**Pull request merged**
